# Generated by Django 4.0.1 on 2022-01-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_alter_cars_avg_rate_alter_rate_rates_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='avg_rate',
            field=models.FloatField(null=True),
        ),
    ]
