# Generated by Django 4.0.1 on 2022-01-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0003_alter_cars_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rates_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sum_rate',
            field=models.IntegerField(default=0),
        ),
    ]
